province_ajax_call:
    path:   /province_ajax_call
    defaults: { _controller: TEST2RegistrationBundle:Default:provinceAjaxCall }

test_registration_homepage:
    path:    /
    defaults: { _controller: TEST2RegistrationBundle:Default:index }
